% STARTUP -- This m-file is responsible for setting up the matlab path
% for use with this simulation directory.
%
% Adds the following directories to the matlab path:


function startup()

fprintf(['Excuting start up file\n']);

current_dir     = pwd;
% Run environmental file
% workspace_dir   = getenv("DIR_WORKSPACE");
workspace_dir   = current_dir;

% Add directories to matlab path (but as absolute path, not relative path)
dirs={ ...
    sprintf('%s/main',workspace_dir), ...
    sprintf('%s/setup',workspace_dir), ...
    sprintf('%s/utils',workspace_dir), ...
    sprintf('%s/config',workspace_dir), ...
    sprintf('%s/lib',workspace_dir), ...
    sprintf('%s/lib/wfsc',workspace_dir), ...
    sprintf('%s/lib/masks',workspace_dir), ...
    sprintf('%s/lib/plot',workspace_dir), ...
    sprintf('%s/lib/dm',workspace_dir), ...
    sprintf('%s/lib/utils',workspace_dir), ...
    sprintf('%s/lib/imaging',workspace_dir), ...
    sprintf('%s/lib/propcustom',workspace_dir), ...
    sprintf('%s/lib/Zernike',workspace_dir), ...
    sprintf('%s/lib_external',workspace_dir), ...
    sprintf('%s/lib_external/proper',workspace_dir), ...
    sprintf('%s/lib_external/allcomb',workspace_dir), ...
    sprintf('%s/models',workspace_dir), ...
    '.' ...
     };

for k=1:length(dirs)
  if exist(dirs{k}, 'dir')
      cd(dirs{k});
      fprintf(['Adding ', pwd, ' to the matlab path.\n']);
      addpath(pwd, '-begin');
      cd(current_dir);
  else
    fprintf('Skipping non-existent path %s\n', dirs{k});
  end
end


